name: CI

on:
   push:
      branches:
         - main
   pull_request:

permissions:
   actions: read
   contents: read

env:
   DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
   DISCORD_CLIENT_ID: ${{ secrets.DISCORD_CLIENT_ID }}
   DATABASE_URL: ${{ secrets.DATABASE_URL }}
   FRONT_URL: ${{ secrets.FRONT_URL }}
   AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
   AZURE_AUTHORITY: ${{ secrets.AZURE_AUTHORITY }}
   AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
   SECRET_COOKIE_PASSWORD: ${{ secrets.SECRET_COOKIE_PASSWORD }}
   CRYPT_KEY: ${{ secrets.CRYPT_KEY }}
   HASH_KEY: ${{ secrets.HASH_KEY }}
   NX_CLOUD_ACCESS_TOKEN: ${{ secrets.NX_CLOUD_ACCESS_TOKEN }}

jobs:
   main:
      runs-on: ubuntu-latest

      env:
         # Helps large dependency graphs / native builds
         NODE_OPTIONS: --max-old-space-size=4096
         # Ensure yarn keeps printing (avoids 10m idle timeout)
         YARN_ENABLE_PROGRESS_BARS: true
         YARN_ENABLE_GLOBAL_CACHE: true
         # Slow networks/registry hiccups
         YARN_NPM_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }} # harmless for public npm, useful if you pull GitHub Packages
         # Optional: serialize link step a bit
         YARN_NETWORK_TIMEOUT: 600000

      steps:
         - uses: actions/checkout@v4
           with:
              filter: tree:0
              fetch-depth: 0

         - run: corepack enable
         - uses: actions/setup-node@v4
           with:
              node-version: 20

         # Proper Yarn Berry cache
         - name: Cache Yarn
           uses: actions/cache@v4
           with:
              path: |
                 .yarn/cache
                 .yarn/unplugged
                 .yarn/build-state.yml
                 .yarn/install-state.gz
                 ~/.cache/yarn
              key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
              restore-keys: |
                 ${{ runner.os }}-yarn-

         # Make yarn noisier & less bursty; set once per repo if you prefer
         - name: Yarn CI knobs
           run: |
              yarn config set enableGlobalCache true
              yarn config set networkConcurrency 8
              yarn config set httpTimeout 600000
              yarn config set logFilters --json false

         # Install: inline builds keep logs flowing; --immutable keeps lockfile strict
         - name: Install deps
           run: |
              yarn install --immutable --inline-builds --verbose

         - uses: nrwl/nx-set-shas@v4

         - run: yarn nx affected -t lint test build
         - run: yarn nx fix-ci
           if: always()
