name: CI

on:
   push:
      branches:
         - main
   pull_request:

permissions:
   actions: read
   contents: read

env:
   DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
   DISCORD_CLIENT_ID: ${{ secrets.DISCORD_CLIENT_ID }}
   DATABASE_URL: ${{ secrets.DATABASE_URL }}
   FRONT_URL: ${{ secrets.FRONT_URL }}
   AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
   AZURE_AUTHORITY: ${{ secrets.AZURE_AUTHORITY }}
   AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
   SECRET_COOKIE_PASSWORD: ${{ secrets.SECRET_COOKIE_PASSWORD }}
   CRYPT_KEY: ${{ secrets.CRYPT_KEY }}
   HASH_KEY: ${{ secrets.HASH_KEY }}
   NX_CLOUD_ACCESS_TOKEN: ${{ secrets.NX_CLOUD_ACCESS_TOKEN }}

jobs:
   main:
      runs-on: ubuntu-latest
      steps:
         - uses: actions/checkout@v4
           with:
              filter: tree:0
              fetch-depth: 0

         - run: corepack enable
         - uses: actions/setup-node@v4
           with:
              node-version: 20
              cache: 'yarn'

         - run: yarn install --immutable
         - uses: nrwl/nx-set-shas@v4

         - run: yarn nx affected -t lint test build
         - run: yarn nx fix-ci
           if: always()
