name: CI

on:
   push:
      branches:
         - main
   pull_request:

env:
   DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
   DISCORD_CLIENT_ID: ${{ secrets.DISCORD_CLIENT_ID }}
   DATABASE_URL: ${{ secrets.DATABASE_URL }}
   FRONT_URL: ${{ secrets.FRONT_URL }}
   AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
   AZURE_AUTHORITY: ${{ secrets.AZURE_AUTHORITY }}
   AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
   SECRET_COOKIE_PASSWORD: ${{ secrets.SECRET_COOKIE_PASSWORD }}

jobs:
   main:
      name: Nx Cloud - Main Job
      uses: nrwl/ci/.github/workflows/nx-cloud-main.yml@v0.8
      with:
         number-of-agents: 3
         init-commands: |
            yarn nx-cloud start-ci-run --stop-agents-after="build" --agent-count=3
         parallel-commands: |
            yarn nx-cloud record -- yarn nx workspace-lint
            yarn nx-cloud record -- yarn nx format:check
         parallel-commands-on-agents: |
            yarn nx affected --target=lint --parallel=3
            yarn nx affected --target=test --parallel=3 --ci --code-coverage
            yarn nx affected --target=build --parallel=3

   agents:
      name: Nx Cloud - Agents
      uses: nrwl/ci/.github/workflows/nx-cloud-agents.yml@v0.8
      with:
         number-of-agents: 3
